# Generated by Django 3.0.5 on 2020-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rawComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keluhan', models.TextField()),
            ],
            options={
                'db_table': 'tb_raw_complaints',
            },
        ),
    ]
