# Generated by Django 3.0.5 on 2020-04-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tb_kategori',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tb_status',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('sentimen', models.CharField(choices=[('Negatif', 'Negatif'), ('Positif', 'Positif')], max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiMobile.Kategori')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiMobile.Status')),
            ],
            options={
                'db_table': 'tb_complaints',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=150)),
                ('jabatan', models.CharField(max_length=200)),
                ('status_admin', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin')], max_length=100)),
                ('token', models.TextField(null=True)),
                ('password', models.CharField(max_length=200)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiMobile.Kategori')),
            ],
            options={
                'db_table': 'tb_admin',
            },
        ),
    ]
