# Generated by Django 3.0.5 on 2020-04-21 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0002_admin_complaint_kategori_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='nama',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='apiMobile.Kategori'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='apiMobile.Kategori'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='apiMobile.Status'),
        ),
    ]
