# Generated by Django 3.0.5 on 2020-04-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0004_auto_20200421_1916'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='tb_complaint',
        ),
        migrations.AlterModelTable(
            name='rawcomplaints',
            table='tb_raw_complaint',
        ),
    ]
