# Generated by Django 3.0.5 on 2020-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0005_auto_20200422_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcomplaints',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
