# Generated by Django 3.0.5 on 2020-05-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0006_auto_20200423_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tanggapan',
            field=models.TextField(null=True),
        ),
    ]
