# Generated by Django 3.0.5 on 2020-06-12 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0008_auto_20200520_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
