# Generated by Django 3.0.5 on 2020-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0009_complaint_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(default='user@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nim',
            field=models.CharField(default='000000', max_length=20),
        ),
    ]
