# Generated by Django 3.0.5 on 2020-06-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0010_auto_20200625_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='token',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='apiMobile.Admin')),
            ],
            options={
                'db_table': 'tb_token',
            },
        ),
    ]
