# Generated by Django 3.0.5 on 2020-07-11 13:40

import apiMobile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0012_complaint_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to=apiMobile.models.upload_path)),
                ('img_name', models.CharField(blank=True, default='img', max_length=150, null=True)),
            ],
            options={
                'db_table': 'tb_images',
            },
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
