# Generated by Django 3.0.5 on 2020-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0013_auto_20200711_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='jurusan',
            field=models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Mesin', 'Teknik Mesin'), ('Teknik Pendingin dan Tata Udara', 'Teknik Pendingin dan Tata Udara'), ('Keperawatan', 'Keperawatan')], default='', max_length=200),
        ),
    ]
