# Generated by Django 3.0.5 on 2020-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMobile', '0016_auto_20200721_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='jurusan',
            field=models.CharField(blank=True, choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Mesin', 'Teknik Mesin'), ('Teknik Pendingin Dan Tata Udara', 'Teknik Pendingin Dan Tata Udara'), ('Keperawatan', 'Keperawatan')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='jurusan',
            field=models.CharField(blank=True, choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Mesin', 'Teknik Mesin'), ('Teknik Pendingin Dan Tata Udara', 'Teknik Pendingin Dan Tata Udara'), ('Keperawatan', 'Keperawatan')], default=None, max_length=200, null=True),
        ),
    ]
